### ISSUE TITLE
Providing data in a reproducible way

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/Computing_for_Cancer_Informatics#36]
**Describe the your scope of your content idea**
This is a placeholder issue for where @carriewright11 and I can discuss what kinds of items should be covered in the Sharing data chapter of this course. 

The reproducibility course is linking to this chapter so we don't have to write redundant chapters on this but instead we can tag team it.

**Comment by carriewright11** [comment]
@cansavvy  your course should link to the data course now that I have split them.
repo: https://github.com/jhudsl/Data_Management_for_Cancer_Research
bookdown: https://jhudatascience.org/Data_Management_for_Cancer_Research/

**Comment by cansavvy** [comment]
Great! Thanks for letting me know!

**Comment by carriewright11** [comment]
This is out of date and done :)
